name: E-COMMERCE CI

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
        - name: Github Actions
          uses: actions/checkout@v3

        - name: Node setup
          uses: actions/setup-node@v2
          with:
            node-version: '20'

        - name: Install dependencies
          run: npm install

        - name: Run Cypress test suite
          uses: cypress-io/github-action@v6
          continue-on-error: true
          with:
              browser: firefox
              headless: true
              command: npm run cy:run

        - name: Publish report
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./mochawesome-report
